#!/bin/sh

docker run --rm --network="host" -e SONAR_HOST_URL="http://localhost:9000/" -e SONAR_LOGIN="sqp_996f9a524af1d9649d22f38831119df87c59a6fc" -v "`pwd`:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=test
