#!/bin/sh

docker run --rm --network="host" -e SONAR_HOST_URL="http://localhost:9000/" -e SONAR_LOGIN="sqp_51cf19dc6dfe614ceec6d9d4a58f17da44dd3aea" -v "`pwd`:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=Testing
